export default [
  {
    id: 1,
    name: 'Expresso Tradicional',
    type: 'tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 'R$9,90',
    img: '../../src/assets/expresso.svg',
  },
  {
    id: 2,
    name: 'Expresso Americano',
    type: 'tradicional',
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 'R$9,90',
    img: '../../src/assets/americano.svg',
  },
  {
    id: 3,
    name: 'Expresso Cremoso',
    type: 'tradicional',
    description: 'Café expresso tradicional com espuma cremosa',
    price: 'R$9,90',
    img: '../../src/assets/expresso-cremoso.svg',
  },
  {
    id: 4,
    name: 'Expresso Gelado',
    type: 'tradicional',
    type2: 'gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 'R$9,90',
    img: '../../src/assets/cafe-gelado.svg',
  },
  {
    id: 5,
    name: 'Café com Leite',
    type: 'tradicional',
    type2: 'com leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 'R$9,90',
    img: '../../src/assets/cafe-com-leite.svg',
  },
  {
    id: 6,
    name: 'Latte',
    type: 'tradicional',
    type2: 'com leite',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 'R$9,90',
    img: '../../src/assets/latte.svg',
  },
  {
    id: 7,
    name: 'Capuccino',
    type: 'tradicional',
    type2: 'com leite',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 'R$9,90',
    img: '../../src/assets/capuccino.svg',
  },
  {
    id: 8,
    name: 'Macchiato',
    type: 'tradicional',
    type2: 'com leite',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 'R$9,90',
    img: '../../src/assets/macchiato.svg',
  },
  {
    id: 9,
    name: 'Mocaccino',
    type: 'tradicional',
    type2: 'com leite',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 'R$9,90',
    img: '../../src/assets/mochaccino.svg',
  },
  {
    id: 10,
    name: 'Chocolate Quente',
    type: 'tradicional',
    type2: 'com leite',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 'R$9,90',
    img: '../../src/assets/chocolate-quente.svg',
  },
  {
    id: 11,
    name: 'Cubano',
    type: 'especial',
    type2: 'alcoólico',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 'R$9,90',
    img: '../../src/assets/cubano.svg',
  },
  {
    id: 12,
    name: 'Havaiano',
    type: 'especial',
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 'R$9,90',
    img: '../../src/assets/havaiano.svg',
  },
  {
    id: 13,
    name: 'Áarabe',
    type: 'especial',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 'R$9,90',
    img: '../../src/assets/arabe.svg',
  },
  {
    id: 14,
    name: 'Irlandês',
    type: 'especial',
    type2: 'alcoólico',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 'R$9,90',
    img: '../../src/assets/irlandes.svg',
  },
]
